* luke
** Overview
   Luke is an OTP application that supports the coordination of
   flow-oriented parallel computations like MapReduce.  It was created
   to extract common behaviors in Riak's MapReduce engine.

** Quick Start
   You must have [[http://erlang.org/download.html][Erlang/OTP R13]]
   or later to build Luke. A sane GNU-style build system is required
   if you want to use =make= to build the project.

#+BEGIN_SRC shell
git clone git://github.com/basho/luke.git
cd luke
make
# or
./rebar compile
#+END_SRC
   
   To get edoc documentation for Luke, build the "docs" make target.

#+BEGIN_SRC shell
make docs
# or
./rebar doc
#+END_SRC

** Contributing
   We encourage contributions to Luke from the community.

   1. Fork the =luke= repository on [[https://github.com/basho/luke][Github]].
   2. Clone your fork or add the remote if you already have a clone of
      the repository.
#+BEGIN_SRC shell
git clone git@github.com:yourusername/luke.git
# or
git remote add mine git@github.com:yourusername/luke.git
#+END_SRC
   3) Create a topic branch for your change.
#+BEGIN_SRC shell
git checkout -b some-topic-branch
#+END_SRC
   4) Make your change and commit. Use a clear and descriptive commit
      message, spanning multiple lines if detailed explanation is
      needed.
   5) Push to your fork of the repository and then send a pull-request
      through Github.
#+BEGIN_SRC shell
git push mine some-topic-branch
#+END_SRC
   6) A Basho engineer or community maintainer will review your patch
      and merge it into the main repository or send you feedback.

